### ISSUE TITLE
Files plugin TODO:

### ISSUE THREAD

**Issue by Mingling94** [NebulousLabs/Sia-UI#174]
### Easy
- [x] Display folders before files and sort alphabetically
- [x] Aggregate share selected shareascii selected
- [ ] Hotkey delete, select (w/ arrow keys) and other behaviors
- [ ] Darken text and redesign (overall for plugins)
- [x] Search bar
### Hard
- [ ] Ensure recursive folder upload works
- [ ] Drag files and drop to folder to move around
- [ ] Drag and drop upload

**Comment by DavidVorick** [comment]
Files plugin is on its way to being revamped again
